/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as PackageCatalogRouteImport } from './routes/package-catalog'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const PackageCatalogRoute = PackageCatalogRouteImport.update({
  id: '/package-catalog',
  path: '/package-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/bookings': typeof BookingsRoute
  '/customers': typeof CustomersRoute
  '/insights': typeof InsightsRoute
  '/package-catalog': typeof PackageCatalogRoute
  '/packages': typeof PackagesRoute
  '/payments': typeof PaymentsRoute
  '/rooms': typeof RoomsRoute
  '/support': typeof SupportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/bookings': typeof BookingsRoute
  '/customers': typeof CustomersRoute
  '/insights': typeof InsightsRoute
  '/package-catalog': typeof PackageCatalogRoute
  '/packages': typeof PackagesRoute
  '/payments': typeof PaymentsRoute
  '/rooms': typeof RoomsRoute
  '/support': typeof SupportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/bookings': typeof BookingsRoute
  '/customers': typeof CustomersRoute
  '/insights': typeof InsightsRoute
  '/package-catalog': typeof PackageCatalogRoute
  '/packages': typeof PackagesRoute
  '/payments': typeof PaymentsRoute
  '/rooms': typeof RoomsRoute
  '/support': typeof SupportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/bookings'
    | '/customers'
    | '/insights'
    | '/package-catalog'
    | '/packages'
    | '/payments'
    | '/rooms'
    | '/support'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/bookings'
    | '/customers'
    | '/insights'
    | '/package-catalog'
    | '/packages'
    | '/payments'
    | '/rooms'
    | '/support'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/bookings'
    | '/customers'
    | '/insights'
    | '/package-catalog'
    | '/packages'
    | '/payments'
    | '/rooms'
    | '/support'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BookingsRoute: typeof BookingsRoute
  CustomersRoute: typeof CustomersRoute
  InsightsRoute: typeof InsightsRoute
  PackageCatalogRoute: typeof PackageCatalogRoute
  PackagesRoute: typeof PackagesRoute
  PaymentsRoute: typeof PaymentsRoute
  RoomsRoute: typeof RoomsRoute
  SupportRoute: typeof SupportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/package-catalog': {
      id: '/package-catalog'
      path: '/package-catalog'
      fullPath: '/package-catalog'
      preLoaderRoute: typeof PackageCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BookingsRoute: BookingsRoute,
  CustomersRoute: CustomersRoute,
  InsightsRoute: InsightsRoute,
  PackageCatalogRoute: PackageCatalogRoute,
  PackagesRoute: PackagesRoute,
  PaymentsRoute: PaymentsRoute,
  RoomsRoute: RoomsRoute,
  SupportRoute: SupportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
